### ISSUE TITLE
Encrypted data?

### ISSUE THREAD

**Issue by MGlolenstine** [xgladius/wiz-packet-map#1]
So they started encrypting their traffic with the latest update?

I was wondering why none of my logging apps were working...

Any ETA on more information/code?

**Comment by MGlolenstine** [comment]
Found more information [here](https://ethankrein.github.io/On-Wiz/#!index.md).

**Comment by xgladius** [comment]
Sorry, just saw this. Yes, they are using aes-gcm (and specifically crypto++) to achieve packet encryption. The client generates two 16 byte random buffers (key and iv of gcm-aes) every zone change, and sends it to the server using a public key (rsa) the server sent on the initial connection.
