### ISSUE TITLE
Infinite loading screens

### ISSUE THREAD

**Issue by Bobbls** [xgladius/wiz-packet-map#2]
Seems to be whenever you enter a new zone (i assume this is where the encryption key changes) it just seems to hang there forever

**Comment by benjaminmordaunt** [comment]
I'm encountering this issue too. On a zone change/login, the game halts.

**Comment by xgladius** [comment]
> Seems to be whenever you enter a new zone (i assume this is where the encryption key changes) it just seems to hang there forever

Sorry that I just now saw this, I will look into it today and push a fix

**Comment by xgladius** [comment]
@crawben20 @Bobbls #4 fixed
